UIU-2068: fix eslint error in LoanDetails.js
folio-org/ui-users pull request #1663
Opened 2021-03-09 12:22 UTC by Dmitriy-Litvinenko

# Description
- Fix eslint error in LoanDetails.js

# Stories
https://issues.folio.org/browse/UIU-2068

2021-03-09 14:22 UTC, zburke requested changes
~Unless you think this rule has merit, I'm inclined [turn it off directly in `eslint-config-stripes`](https://github.com/folio-org/eslint-config-stripes/pull/77). What do you think?~

2021-03-10 02:53 UTC, zburke reviewed
Now that I've read [the ESLint rule](https://eslint.org/docs/rules/no-return-await) and [the articles it references](https://jakearchibald.com/2017/await-vs-return-vs-return-await/) 100 times, I'm inclined to say the "right" thing here is to simply remove `await` from the picture:
```
return this.onRenew();
```
rather than disable the lint rule, unless somebody can explain to me why `await` is necessary here. 

(Sorry for the whiplash; thank you for your patience while I'm learning.)

2021-03-11 16:12 UTC, Dmitriy-Litvinenko commented
@zburke @mkuklis @annamelnyk Could you please re-review?

2021-03-11 17:23 UTC, mkuklis approved these changes

2021-03-11 18:01 UTC, zburke approved these changes

2021-03-11 18:24 UTC, annamelnyk approved these changes

2021-03-11 22:25 UTC, merged