UIU-2332 create Jest/RTL test for refundTransferClaimReturned.js
folio-org/ui-users pull request #1929
Opened 2021-11-03 07:37 UTC by Mathansivavelmurugesan

Jest/RTL test case with coverage for refundtransferClaimReturned 

![UIU-2332](https://user-images.githubusercontent.com/89525723/140023492-afb04b92-6f3f-4203-8921-765b9bb49307.PNG)

2021-11-03 11:41 UTC, zburke requested changes
The coverage looks great, but some of the data included here seems to be unnecessarily duplicated. Can that be cleaned up? 

Also, you don't need to include the coverage screenshot; coverage on new code is automatically reported in a PR comment by SonarCloud.

2021-11-04 09:19 UTC, Mathansivavelmurugesan commented on src/components/util/refundTransferClaimReturned.test.js
> +};
Changed it into a single object. created it for understanding the flow

2021-11-04 13:16 UTC, zburke approved these changes
LGTM!

2021-11-04 15:34 UTC, mkuklis approved these changes

2021-11-04 16:36 UTC, merged