UIU-2408 create Jest/RTL test for Owners.js
folio-org/ui-users pull request #1958
Opened 2021-11-30 13:11 UTC by Mathansivavelmurugesan

Code coverage and unit testing for Owners.js

2021-11-30 16:16 UTC, mkuklis approved these changes

2021-12-01 11:55 UTC, zburke requested changes
@Mathansivavelmurugesan , I see that you're passing different `dataOptions` values in each of these tests, but the `expect` function is identical for all of them, which surprised me. e.g. in the first test, shouldn't we check that `test1256` is _not_ rendered since `filterShared` is true? 

@zburke , My bad checked those with debug but didnt add the cases, now I have added those scenarios.

2021-12-01 17:16 UTC, zburke approved these changes

2021-12-01 18:44 UTC, mkuklis approved these changes

2021-12-02 06:32 UTC, merged