UIU-2317 create Jest/RTL test for BulkClaimReturnedModal.js
folio-org/ui-users pull request #1968
Opened 2021-12-09 09:49 UTC by Mathansivavelmurugesan

Test cases and code coverage for BulkClaim Returned Modal component.

2021-12-09 13:41 UTC, zburke requested changes
Note the console error "prop `mutator.activeAccount` is marked as required in `BulkClaimReturnedModal`" that should be easy to address. While I'm all for minimizing the amount of mocked-props we need to create to test stuff, we should likewise minimize console noise during tests, so `console.error` complaints should definitely get fixed. Related, MCL adds a bunch of console warnings about null values, and while those can be ignored since we're not actually testing MCL here, I'm like 50/50 on whether we should fill in those props anyway in order to have a cleaner console during the tests. 

Additionally, the "React does not recognize the `data-test-bulk-claim-returned-additionalInfo`" `console.error` is on code that predates this PR, but can easily be cleaned up just by de-camel-casing `additionalInfo` to `additional-info` so react doesn't (wrongly) apply it to the underlying DOM element, since that's what [react loves to do with camelCased props](https://reactjs.org/docs/dom-elements.html).

2021-12-14 13:26 UTC, Mathansivavelmurugesan commented on src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.test.js
> +    log: () => {},
The core mock passed stripes data only if it is connected via stripesconnect. While rendering child components the mock data is not traversered and I get null so using it locally for each components

2021-12-14 14:15 UTC, zburke commented on src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.test.js
> +    log: () => {},
Ah, ok, I didn't understand that before. Another route that some other tests have taken in this situation is to use [`buildStripes`](https://github.com/folio-org/ui-users/blob/b5aa71bd1a6fc894e5a32572888ef33967d72dcf/src/components/Wrappers/withProxy.test.js#L86-L91)

2021-12-14 14:15 UTC, zburke approved these changes

2021-12-14 14:19 UTC, mkuklis approved these changes

2021-12-20 13:51 UTC, merged