UIU-1686: Accessibility: Form elements must have labels
folio-org/ui-users pull request #2054
Opened 2022-02-22 09:39 UTC by OleksandrHladchenko1

Purpose
---------
* Add label for form elements

Approach
-----------
* Added aria-label for form elements

Refs
-----
https://issues.folio.org/browse/UIU-1686

2022-02-22 15:28 UTC, mariia-aloshyna approved these changes

2022-02-28 14:53 UTC, mariia-aloshyna commented
Hi @zburke Could you take a look, please? Thank you!

2022-02-28 19:51 UTC, zburke reviewed
Hmmmmmm. It feels like a simpler, and maybe better refactor than adding `aria-label`, would be moving from 
```
<Row>
  <Col xs={12}>
    <b><FormattedMessage id="ui-users.charge.owner.label" /></b>
  </Col>
</Row>
<Row>
  <Col xs={12}>
    <Field
      name="ownerId"
      ...
    />
  </Col>
</Row>
```
to 
```
<Row>
  <Col xs={12}>
    <Field
      name="ownerId"
      label={<FormattedMessage id="ui-users.charge.owner.label" />}
      ...
    />
</Row>
```
What do you think?

2022-03-01 11:54 UTC, mariia-aloshyna commented
> Hmmmmmm. It feels like a simpler, and maybe better refactor than adding `aria-label`, would be moving from
> 
> ```
> <Row>
>   <Col xs={12}>
>     <b><FormattedMessage id="ui-users.charge.owner.label" /></b>
>   </Col>
> </Row>
> <Row>
>   <Col xs={12}>
>     <Field
>       name="ownerId"
>       ...
>     />
>   </Col>
> </Row>
> ```
> 
> to
> 
> ```
> <Row>
>   <Col xs={12}>
>     <Field
>       name="ownerId"
>       label={<FormattedMessage id="ui-users.charge.owner.label" />}
>       ...
>     />
> </Row>
> ```
> 
> What do you think?

Hi @zburke ! Looks good, but when I tried to implement this it didn't work. Weird...
Then I figured out that implementation of `Select` component doesn't allow this because of the `aria-label` property, since this applies the `sr-only` class to the label, and the user literally does not see the label. I would propose to make changes in the `Select` component but not in the scope of this task.
https://github.com/folio-org/stripes-components/blob/master/lib/Select/Select.js#L180

2022-03-01 16:00 UTC, zburke requested changes
All the form components from stripes-components take a `label` prop which will automatically configure the right styles and a11y attributes; thus `<SomeInput label=... />` should be the first choice when building a form. If that can't be done, the next choice for labeling a field is with a [`<Label>`](https://github.com/folio-org/stripes-components/tree/1ec88ef173b9b69214550287df706e19bb731e6a/lib/Label) that includes a machine-readable `id` prop which can be passed to the `<Field>` it corresponds to with `aria-labelledby`. The last resort, when a field has no visual label, is a human-readable `aria-label` property. 

If converting to `<Field label... />` is too much work in the scope of this ticket, I respect that. But if the approach you take is `aria-label`, the value for that prop should be a human-readable value.

2022-03-03 10:55 UTC, mariia-aloshyna commented on src/settings/CommentRequiredForm.js
> +          aria-label={name}
Hi @zburke Updated the PR. Please, take a look

2022-03-04 15:14 UTC, zburke approved these changes

2022-03-04 17:18 UTC, merged