UIU-1257: Focus should be on pane header title when Loans list is open
folio-org/ui-users pull request #2057
Opened 2022-02-25 12:03 UTC by Javokhir12

## Purpose
- Currently when you access the Open/Closed Loans list, the initial focus is outside the page.
- Requirement: initial focus should be on pane header title.
- Refs: https://issues.folio.org/browse/UIU-1257

## Approach
- Pass `paneTitleRef` prop to `Pane` component to move focus on pane header on `Mount`

2022-02-25 12:25 UTC, zburke requested changes

2022-02-25 12:25 UTC, zburke commented on src/views/LoansListing/LoansListing.js
> +    // eslint-disable-next-line react/sort-comp
Don't disable lint. The reformatting here is minor; please just do what it asks :) You can rearrange things here, or move the `createRef` line into a constructor. The acctual cDM methods looks good, of course.

2022-02-25 16:10 UTC, zburke approved these changes
LGTM! Go ahead and "Squash and merge" unless you want to wait for another approval. Thank you!

2022-02-25 17:04 UTC, mkuklis approved these changes

2022-02-28 14:51 UTC, mariia-aloshyna commented
Hi @Javokhir12 Can this PR be merged?

2022-02-28 14:54 UTC, Javokhir12 commented
> Hi @Javokhir12 Can this PR be merged?

Hi @mariia-aloshyna . Yes we can

2022-02-28 14:55 UTC, merged