UI u 2620
folio-org/ui-users pull request #2172
Opened 2022-06-13 16:35 UTC by ymacedor

2022-06-26 17:44 UTC, mkuklis requested changes

2022-06-26 17:44 UTC, mkuklis commented on src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
> +  onChangeFeeFine(feeFineId) {
@ymacedor the `onChagenFeeFine` is attached to `onChange` event:

https://github.com/folio-org/ui-users/blob/d48a3bc02fd5a5e32395544fe0bc801c890a973a/src/components/Accounts/ChargeFeeFine/FeeFineInfo.js#L97

which passes an event object. Is there a reason you changed it here to `feeFineId`?

2022-06-29 14:03 UTC, mkuklis commented
@ymacedor it looks like one of the tests started failing after this change:

https://github.com/folio-org/ui-users/runs/7101624308?check_suite_focus=true#step:12:2838

Could you please make sure it passes? Otherwise we won't be able to merge this.

2022-06-29 18:26 UTC, ymacedor commented
@mkuklis  I have already fixed the tests

2022-06-30 13:18 UTC, mkuklis commented
@ymacedor thank you. I will try to merge this in: https://github.com/folio-org/ui-users/pull/2172 soon.

You should also now have access to `folio-org/ui-users` so in the future please just clone that repo and open PRs from that remote (instead of cloning ui-users). That should simplify merging your PRs.

2022-06-30 13:38 UTC, closed without merging