UIU-2491 Create permission for "Lost items requiring actual costs" processing page
folio-org/ui-users pull request #2220
Opened 2022-08-23 13:33 UTC by artem-blazhko

## Purpose
Users with "Users: Can process lost items requiring actual cost" permission should be able to open the "Lost items requiring actual costs" page using the link in action menu (see screenshot below).
If a user doesn't have permission he/she should see the appropriate error page (see screenshot below).

## Refs
[UIU-2491](https://issues.folio.org/browse/UIU-2491)

## Screenshots
![image](https://user-images.githubusercontent.com/42437614/186170747-1722955f-f28d-48f6-92e6-7fa01067a8b7.png)

![image](https://user-images.githubusercontent.com/42437614/186171174-038e7a27-2df4-44a0-b69c-c495c1999195.png)

2022-08-23 13:59 UTC, Dmitriy-Litvinenko approved these changes

2022-08-23 21:05 UTC, zburke requested changes
Code LGTM but other permissions are `namedLikeThis` `not-like-this` so you should follow the established convention.

2022-08-24 13:26 UTC, artem-blazhko commented
> Code LGTM but other permissions are `namedLikeThis` `not-like-this` so you should follow the established convention.

@zburke thank you for your comment. 
I tried to use the most popular approach in `package.json`  file. I see different approaches there and it seems that `approach-with-dashes` is more popular than `camelCase` approach. 
Could you clarify if there is any documentation with code conventions? 
Thank you in advance.

2022-08-24 13:50 UTC, zburke approved these changes
@artem-blazhko, when I reviewed this PR the first time I only looked at the few lines in the diff in `en.json`, and that made this new value look like an outlier. When you back up and look at the whole file, it's clear that I'm wrong about camelCase being the standard. 

In short, ugh, you're right, dash-words is at least as common as any other naming convention in `package.json`. That's definitely unfortunate, but it's also definitely not a problem specifically with this PR. Thanks for setting me straight!

2022-08-24 17:26 UTC, merged