UIU-2732: Fix problem with Claimed return button
folio-org/ui-users pull request #2284
Opened 2022-11-22 10:19 UTC by Dmitriy-Litvinenko

## Purpose
Fix problem with Claimed return button. Button should be disabled after click.

## Refs
https://issues.folio.org/browse/UIU-2732

2022-11-22 16:02 UTC, zburke requested changes
Sorry, it's really hard to figure out what's actually happening here given the very generic "Fix problem" in the PR description and "toggleButton" variables in the code. Additionally, new functionality needs new tests. Maybe you need a more extensive mock of the Modal opened by LoanActionDialog so you can validate whether its buttons are enabled based on the `inProgress` prop you're passing through?

2022-11-23 10:00 UTC, Dmitriy-Litvinenko commented on CHANGELOG.md
> +* Fix problem with Claimed return button. Refs UIU-2732.
Fixed

2022-11-23 11:27 UTC, Dmitriy-Litvinenko commented on src/components/Wrappers/withClaimReturned.js
> +
Fixed

2022-11-23 11:32 UTC, Dmitriy-Litvinenko commented
@zburke Could you please re-review?
@mkuklis Could you please review?

2022-11-23 11:56 UTC, zburke reviewed
The better variable names make this much easier to follow. Thank you! But now that I see what's going on, I have a question: `<ModalContent>` seems like a generic component. Does it really need to know about `claimedReturnInProgress` and `declarationInProgress`? It feels instead like there should be a generic `isInProgress` prop so we don't have to add a new prop to it every time we want to call it from a new component, i.e.
```
const isConfirmButtonDisabled = !additionalInfo || claimReturnedInProgress || declarationInProgress;
```
can be rewritten as 
```
const isConfirmButtonDisabled = !additionalInfo || isInProgress;
```
Good idea, bad idea?

2022-11-23 12:52 UTC, zburke approved these changes
Sorry for the run-around from generic props to implementation-specific props and back again. Now that I have a solid understanding of how this works, and with UIU-2736 in the picture, this looks great!

2022-11-23 12:53 UTC, merged