Implement "Do not bill actual cost" functionality
folio-org/ui-users pull request #2311
Opened 2023-01-12 13:10 UTC by artem-blazhko

## Purpose
Implement "Do not bill actual cost" functionality on the "Lost items requiring actual cost page".

## Refs
[UIU-2705](https://issues.folio.org/browse/UIU-2705)

## Screenshots
### Do not bill modal
![image](https://user-images.githubusercontent.com/42437614/212074423-43088300-ec75-4923-8070-e506781d2e4e.png)

### Confirm do not bill modal
![image](https://user-images.githubusercontent.com/42437614/212074484-d0eec8c8-24d3-4377-8f34-0b7e01246c3b.png)

### Success message and "Not billed" label
![image](https://user-images.githubusercontent.com/42437614/212074667-ca7d60da-888e-4370-9329-26eaece04eba.png)

2023-01-12 15:49 UTC, Dmitriy-Litvinenko approved these changes

2023-01-12 17:51 UTC, artem-blazhko commented on src/views/LostItems/LostItemsListContainer/components/LostItemsList/LostItemsList.js
> +              <b><FormattedMessage id="ui-users.lostItems.recordStatus.billed" />: {getBilledAmount(actualCostRecord.id, billedRecords)}</b>
Thank you. Fixed

2023-01-17 14:25 UTC, Terala-Priyanka requested changes
@artem-blazhko 
I do not have much idea on the functionality flow mentioned in this ticket. Code looks good to me. Could you please add more tests to further increase the coverage? - specifically on file /src/views/LostItems/LostItemsListContainer/components/LostItemsList.js

Also, can you investigate if the code smell can be fixed too?

2023-01-18 10:44 UTC, artem-blazhko commented
> @artem-blazhko I do not have much idea on the functionality flow mentioned in this ticket. Code looks good to me. Could you please add more tests to further increase the coverage?
> 
> 1. specifically on file /src/views/LostItems/LostItemsListContainer/components/LostItemsList.js
> 2. if you think adding tests for file src/routes/LostItemsContainer.js, does not take huge effort, please accommodate it.
> 
> Also, Could you investigate if the code smell can be fixed too?

Code smell is fixed. Code coverage of LostItemsList.js file increased.
Also, we have [a story](https://issues.folio.org/browse/UIU-2769) to increase code coverage of "Actual cost" functionality.

2023-01-18 12:57 UTC, Terala-Priyanka approved these changes

2023-01-18 15:11 UTC, merged