UIU-2966 - initial commit to display item title and barcode as text f…
folio-org/ui-users pull request #2597
Opened 2023-11-27 13:06 UTC by Terala-Priyanka

…or dcb virtual item.

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-11-28 11:17 UTC, Dmytro-Melnyshyn approved these changes

2023-11-28 15:22 UTC, ryandberger commented on src/views/LoanDetails/LoanDetails.js
>        const titleTodisplay = (title.length >= 77) ? `${title.substring(0, 77)}...` : title;
I know you didn't add this, but while you're here, can you move this magic number to a constant?

2023-11-28 15:23 UTC, ryandberger approved these changes

2023-11-29 12:02 UTC, zburke requested changes
This is a great start but should handle a11y correctly. I'm glad to see DCB UUIDs stored in constants, but the fact that such constants need to exist at all still gives me the willies.

2023-11-30 10:28 UTC, Terala-Priyanka commented on src/views/LoanDetails/LoanDetails.js
> +              </Link>
done

2023-12-04 11:31 UTC, zburke approved these changes

2023-12-05 09:36 UTC, merged