UIU-3152 - Add 'PreferredEmailCommunication' field to User Profile
folio-org/ui-users pull request #2707
Opened 2024-06-17 08:42 UTC by manvendra-s-rathore

[UIU-3152](https://folio-org.atlassian.net/browse/UIU-3152) -  Add 'PreferredEmailCommunication' field in Contact Information Accordion in User Profile.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-06-18 11:26 UTC, Dmitriy-Litvinenko commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +  { label: 'Programs', value: 'Programs' },
Could you please clarify do we need use react-intl for labels?

2024-06-18 11:26 UTC, Dmitriy-Litvinenko commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +            id="adduser_preferredEmailCommunication"
Could you please clarify do we need use one notation here (just for example camel case notation)?

2024-06-18 11:26 UTC, Dmitriy-Litvinenko commented on src/components/UserDetailSections/ContactInfo/ContactInfo.js
> +            value={_.get(user, ['preferredEmailCommunication'], '-').join(', ')}
Could you please clarify can we move this to function?

2024-06-18 11:29 UTC, Dmitriy-Litvinenko commented on src/components/UserDetailSections/ContactInfo/ContactInfo.js
> +            value={_.get(user, ['preferredEmailCommunication'], '-').join(', ')}
Could you please clarify can we use `import { NoValue } from '@folio/stripes/components';` instead of '-'?

2024-06-19 06:20 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +            aria-required="true"
1. Could you recheck if "aria-required" attribute/prop is needed here?

2024-06-19 06:29 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +  ),
isn't this prop always array of strings?

2024-06-19 06:32 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.test.js
Although the coverage on this file reaches 100%, I think you need to add few unit tests to test the functionality of preferredEmailComm

2024-06-19 06:38 UTC, Terala-Priyanka commented on src/components/UserDetailSections/ContactInfo/ContactInfo.js
No test file exists for this code.
Please evaluate the effort against your bandwidth and if it is simple, please create one to cover your scenarios. 
It is also fine to either have a ticket as tech debt for entire test file or for those scenarios that are beyond the scope of your implementation.

2024-06-19 06:41 UTC, Terala-Priyanka requested changes

2024-06-19 06:41 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +  }, []);
Probably a state is not required here. Could you evaluate if this can be handled by a utility function?

2024-06-21 05:33 UTC, manvendra-s-rathore commented on src/components/UserDetailSections/ContactInfo/ContactInfo.js
The entire file's test case can be covered in a tech-debt. I have created a ticket for this - https://folio-org.atlassian.net/browse/UIU-3157.

2024-06-24 04:46 UTC, Terala-Priyanka approved these changes
Apart from minor comments posted, rest all LGTM. Please address them and merge the PR. I think my re-review is not needed further.

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.test.js
> +    expect(screen.getAllByLabelText('ui-users.contact.preferredEmailCommunication')[0]).toBeInTheDocument();
1. Could you write a new test with title "should render preferred email communication field"?
2. Could you also refactor the title of this test to "should render address list"?

I know you are not the author of the original test. But could you correct what is already existing here?
Best practice is to have one test one assertion. Also, a unit test title should start with "should".

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.test.js
> +    const emailInput = screen.getAllByRole('textbox', { name: /email/i })[0];
Could update the title of test to "should render email field" ?

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/components/EditSections/EditContactInfo/EditContactInfo.test.js
> +    expect(document.querySelector('[id="adduserPreferredEmailCommunication-input"]'));
could you complete the assertion here? may be toBeDisabled()?

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/views/UserEdit/UserEdit.js
> +
```suggestion
  formatPrefEmailCommPayload = prefEmailComm => (
    prefEmailComm?.map(option => option.value)
  )

```

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/views/UserEdit/UserEdit.js
to be consistent with rest of the code, place all const declarations in immediate lines.

2024-06-24 04:46 UTC, Terala-Priyanka commented on src/views/UserEdit/UserEdit.js
> -
retain this space

2024-06-24 05:18 UTC, merged