UIU-3170 - Bump up users okapi interface to 16.2 and fix possible NPE
folio-org/ui-users pull request #2716
Opened 2024-07-09 06:30 UTC by Terala-Priyanka

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-07-09 13:19 UTC, OleksandrHladchenko1 requested changes
Add unit tests please

2024-07-09 13:30 UTC, Terala-Priyanka commented
> Add unit tests please

@OleksandrHladchenko1 
Request you to take note of the PR description above

2024-07-09 13:32 UTC, OleksandrHladchenko1 approved these changes

2024-07-11 06:38 UTC, manvendra-s-rathore approved these changes

2024-07-11 07:53 UTC, vashjs approved these changes

2024-07-11 08:21 UTC, OleksandrHladchenko1 approved these changes

2024-07-11 08:21 UTC, OleksandrHladchenko1 commented on src/components/EditSections/EditContactInfo/EditContactInfo.js
> +  const displaypreferredEmailCommunications = Boolean(stripes.hasInterface('users', '16.2'));
```suggestion
  const displayPreferredEmailCommunications = Boolean(stripes.hasInterface('users', '16.2'));
```
Use camel case here please

2024-07-11 08:47 UTC, merged