UIU-3208 Open loans: Print Due date receipt for single open loans
folio-org/ui-users pull request #2751
Opened 2024-10-06 20:46 UTC by vashjs

After this PR merged, new buttons will be added for printing Due date receipt for single open loan. Refs: [UIU-3208](https://folio-org.atlassian.net/browse/UIU-3208)

Scenarios Covered:

- Display "Print due date receipt" for open loans in action dropdown and details page.
- Don't show the option for closed loans.
- Generate a due date receipt in PDF format for a selected open loan via dropdown or from details page
- Checkbox styling updated

![print](https://github.com/user-attachments/assets/d0e1af31-9a5c-49e2-9c0e-51512c1d62f2)

2024-10-07 10:49 UTC, UladzislauKutarkin approved these changes

2024-10-07 15:51 UTC, Dmytro-Melnyshyn requested changes

2024-10-07 15:51 UTC, Dmytro-Melnyshyn commented on src/hooks/usePrintData/usePrintData.test.js
> +import { renderHook } from '@testing-library/react-hooks';
Please import `renderHook` from `@folio/jest-config-stripes/testing-library/react`.

2024-10-07 15:51 UTC, Dmytro-Melnyshyn commented on package.json
> +    "@testing-library/react-hooks": "^8.0.1",
This module uses `@folio/jest-config-stripes`, please use it instead of `@testing-library`.

2024-10-08 07:56 UTC, Dmytro-Melnyshyn approved these changes

2024-10-08 09:11 UTC, merged